# Arquivo básico de configuração para Jekyll (_config.yml)

# Informações do site
title: "Nome do Seu Site"
description: "Descrição do seu site para aparecer em motores de busca"
url: "https://skaduhs5232.github.io" # URL raiz do site
baseurl: "/ThiagoSampaioPortifolio"  # Subdiretório do projeto (se aplicável)

# Arquivos e diretórios a serem ignorados pelo Jekyll
exclude:
  - "README.md"  # Exemplo, exclua o que não quer incluir na build

# Configurações para Sass (se estiver usando SCSS)
sass:
  style: compressed  # Remove para CSS padrão

# Plugins opcionais, instale apenas os necessários no Gemfile
plugins:
  - jekyll-seo-tag         # Plugin para SEO
  - jekyll-sitemap         # Cria um sitemap.xml automaticamente
  - jekyll-feed            # Cria um feed RSS automaticamente
  - jekyll-paginate        # Adiciona paginação em blogs
  - jekyll-relative-links  # Ajusta links relativos automaticamente

# Configuração para Markdown
markdown: kramdown

# Tema do Jekyll
theme: minima  # Substitua pelo tema escolhido

# Configurações adicionais para GitHub Pages
github:
  is_project_page: true

# Configurações para posts
future: true       # Permite posts com data futura
show_drafts: false # Mostra rascunhos (false para não exibir)

# Permissões e metadados do autor
author: "Seu Nome"
email: "seu-email@exemplo.com"
